spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.2.133:1521:sytestdb
    username: JAVA_SAP
    password: JAVA_SAP_20200408
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sypm.check.bean

server:
  port: 8098

logging:
  level:
    com.sypm.check.mapper: trace
